### ISSUE TITLE
A Bug 

### ISSUE THREAD

**Issue by 1zhangyy1** [ramyma/A8R8_ComfyUI_nodes#4] opened 2024-07-17 09:44 UTC
Hello, I've noticed a conflict with the ipadapter. When the latent batch size is even, my workflow operates normally, but when it's an odd number, an error occurs. This is my workflow.
![workflow](https://github.com/user-attachments/assets/3515fe6e-9ff3-4a82-9ccd-0a071de88db9)

Error occurred when executing KSampler:

shape '[5, -1, 10, 64]' is invalid for input of size 40960

**Comment by ramyma** [comment] 2024-07-18 00:03
You're right, I can add a workaround to handle this pragmatically until I figure out a more permanent solution.

**Comment by ramyma** [comment] 2024-08-18 12:02
I finally had some time to push the fix.
Just set `ip_adapter_active` to true to make it work with an even number of regions.

![image](https://github.com/user-attachments/assets/5d7e8e9d-c8eb-4fa7-aa84-311a0cf4b3fd)

**Comment by 1zhangyy1** [comment] 2024-08-18 12:05
> I finally had some time to push the fix. Just set `ip_adapter_active` to true to make it work with an even number of regions.
> 
> ![image](https://private-user-images.githubusercontent.com/14105815/358903899-5d7e8e9d-c8eb-4fa7-aa84-311a0cf4b3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODI5OTUsIm5iZiI6MTcyMzk4MjY5NSwicGF0aCI6Ii8xNDEwNTgxNS8zNTg5MDM4OTktNWQ3ZThlOWQtYzhlYi00ZmE3LWFhODQtMzExYTBjZjRiM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEyMDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZmQ4NGYwMzJmNDNmZjU3Mjc0NzgzMWNhOWQ0MWJiZGM2YTllNzA1MGI3YjUyZDI3NjNmNDYwNDM2NjkwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dl4mGbKcguW-bu1wOzuEhrWdeaUDN0hf8jGLUuKtWUU)



> I finally had some time to push the fix. Just set `ip_adapter_active` to true to make it work with an even number of regions.
> 
> ![image](https://private-user-images.githubusercontent.com/14105815/358903899-5d7e8e9d-c8eb-4fa7-aa84-311a0cf4b3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODI5OTUsIm5iZiI6MTcyMzk4MjY5NSwicGF0aCI6Ii8xNDEwNTgxNS8zNTg5MDM4OTktNWQ3ZThlOWQtYzhlYi00ZmE3LWFhODQtMzExYTBjZjRiM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDEyMDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZmQ4NGYwMzJmNDNmZjU3Mjc0NzgzMWNhOWQ0MWJiZGM2YTllNzA1MGI3YjUyZDI3NjNmNDYwNDM2NjkwMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dl4mGbKcguW-bu1wOzuEhrWdeaUDN0hf8jGLUuKtWUU)

thanks🥰love you🥰🥰

**Comment by ramyma** [comment] 2024-08-18 12:16
@1zhangyy1 please close the issue if the issue is resolved for you, thanks!

**Closed** 2024-08-18 12:17 UTC
